### ISSUE TITLE
[Feat] - Adicionar o input de e-mail e o botão "Vamos lá"

### ISSUE THREAD

**Issue by rmuliterno** [caiquelourencette/first-repo#4]
Logo depois do texto do centro, colocar um input tipo texto com placeholder "Email" e um botão do lado com o texto de "Vamos lá".

Acho que o desafio pra esse vai ser instalar uma lib de ícones e fazer a implementação, se eu não me engano aquele ícone é o **BsChevronRight**.

https://react-icons.github.io/react-icons/

Lembra de usar `yarn add` ao invés de `npm install` para manter o padrão do projeto.

![2021-08-05_09-59](https://user-images.githubusercontent.com/45672566/128354695-a6a00bd2-dca0-486d-8885-3088d6fb5b56.png)

Também, se conseguir pegar o que está escrito no input e dar um `console.log()` no que foi escrito ao clicar no botão vai ser bem maneiro

**Comment by caiquelourencette** [comment]
eu mudei um pouco o tamanho do input junto do button para encaixar melhor, dá uma olhada, qualquer coisa volta como estava

**Comment by rmuliterno** [comment]
Peguei a versão mais recente aqui e estava assim:

![2021-08-12_12-25](https://user-images.githubusercontent.com/45672566/129224015-4bdf160b-b95c-480f-ae86-74c2f34d46f0.png)

O que está rolando é que o input está com um padding e borda no eixo x e o botão não, aí o input aparece maior do que o botão. Isso é caso de estilização padrão desses elementos, não foi algo que você colocou.

Só tirando a borda e o padding do botão e do input já ficou assim:

![2021-08-12_12-29](https://user-images.githubusercontent.com/45672566/129224621-9f00c30c-22e5-4cc8-93af-55276e35ac0d.png)

Lembra de tirar só do eixo x, da pra tirar usando `padding-bottom` e `padding-top` (também funciona com border) ou usar aquele esquema lá.

`padding: 0 2px 0 10px;`
Nesse caso fica 0px de padding no topo, 2px de padding na direita, 0px de padding embaixo e 10px de padding na esquerda

@caiquelourencette
